spring.application.name=Workspace

spring.datasource.url=jdbc:postgresql://localhost:5433/workspace_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
